#!/usr/bin/env python3
# fetch_doh_spki_pins.py -- extract SHA-256 SPKI pins for DoH resolvers.
#
# Run from the repo root:
#
#     py scripts/fetch_doh_spki_pins.py
#
# For each resolver listed below, this script:
#   1. Opens a TLS 1.2+ connection to <host>:443 with ALPN "http/1.1".
#   2. Retrieves the leaf certificate (DER).
#   3. Parses the SubjectPublicKeyInfo field and hashes it SHA-256.
#   4. Prints the hash as a C byte-array literal suitable for pasting
#      into the kResolvers[] table in src/dns.c.
#
# NOTE: cert rotations invalidate the pin. Re-run whenever DoH auth
# starts failing after a resolver rotates. The printed output includes
# the cert expiry as a hint of how soon you'll need to do that again.
#
# Dependencies: Python 3.10+ stdlib only (ssl, socket, hashlib, struct).

from __future__ import annotations

import hashlib
import socket
import ssl
import sys
from datetime import datetime, timezone

RESOLVERS = [
    ("cloudflare-dns.com", 443, "cloudflare"),
    ("dns.quad9.net",      443, "quad9"),
    ("dns.google",         443, "google"),
    ("dns.nextdns.io",     443, "nextdns"),
    ("dns.mullvad.net",    443, "mullvad"),
]


def fetch_leaf_der(host: str, port: int) -> bytes:
    ctx = ssl.create_default_context()
    ctx.set_alpn_protocols(["http/1.1"])
    ctx.minimum_version = ssl.TLSVersion.TLSv1_2
    with socket.create_connection((host, port), timeout=10) as raw:
        with ctx.wrap_socket(raw, server_hostname=host) as tls:
            der = tls.getpeercert(binary_form=True)
            if not der:
                raise RuntimeError(f"{host}: server did not present a certificate")
            return der


def _read_tlv(buf: bytes, i: int) -> tuple[int, int, int, int]:
    tag = buf[i]
    j = i + 1
    length = buf[j]
    j += 1
    if length & 0x80:
        n = length & 0x7F
        length = int.from_bytes(buf[j:j + n], "big")
        j += n
    return tag, i, j, j + length


def extract_spki_and_expiry(cert_der: bytes) -> tuple[bytes, datetime]:
    # outer SEQUENCE (Certificate)
    tag, _, cs, _ = _read_tlv(cert_der, 0)
    assert tag == 0x30
    tag, _, ts, _ = _read_tlv(cert_der, cs)
    assert tag == 0x30
    p = ts

    if cert_der[p] == 0xA0:                 # [0] EXPLICIT version
        _, _, _, p_end = _read_tlv(cert_der, p)
        p = p_end
    _, _, _, p = _read_tlv(cert_der, p)     # serialNumber
    _, _, _, p = _read_tlv(cert_der, p)     # signature
    _, _, _, p = _read_tlv(cert_der, p)     # issuer
    _, _, vs, ve = _read_tlv(cert_der, p)   # validity
    _, _, _, nb_end = _read_tlv(cert_der, vs)                  # notBefore
    na_tag, _, na_cs, na_ce = _read_tlv(cert_der, nb_end)      # notAfter
    na_bytes = cert_der[na_cs:na_ce]
    if na_tag == 0x17:
        s = na_bytes.decode("ascii")
        y = int(s[0:2]); y += 2000 if y < 50 else 1900
        expiry = datetime(y, int(s[2:4]), int(s[4:6]),
                          int(s[6:8]), int(s[8:10]), int(s[10:12]),
                          tzinfo=timezone.utc)
    else:
        s = na_bytes.decode("ascii")
        expiry = datetime(int(s[0:4]), int(s[4:6]), int(s[6:8]),
                          int(s[8:10]), int(s[10:12]), int(s[12:14]),
                          tzinfo=timezone.utc)
    p = ve
    _, _, _, p = _read_tlv(cert_der, p)                # subject
    _, hdr, _, ce_spki = _read_tlv(cert_der, p)        # SPKI
    spki_der = cert_der[hdr:ce_spki]
    return spki_der, expiry


def main() -> int:
    print("// Generated by scripts/fetch_doh_spki_pins.py")
    print("// Paste each line into the matching entry of kResolvers[] in src/dns.c.\n")
    rc = 0
    for host, port, label in RESOLVERS:
        try:
            der = fetch_leaf_der(host, port)
            spki, expiry = extract_spki_and_expiry(der)
            pin = hashlib.sha256(spki).digest()
            lit = ", ".join(f"0x{b:02x}" for b in pin)
            print(f"// {label}: {host}  (leaf expires {expiry.isoformat()})")
            print(f"// spki_pin = {{ {lit} }}\n")
        except Exception as e:  # pragma: no cover -- network errors
            print(f"// {label}: {host}  FAILED: {e}\n")
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
